# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 19:15
from __future__ import unicode_literals

from django.db import migrations
import djfractions.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=djfractions.models.fields.DecimalFractionField(coerce_thirds=True, decimal_places=3, limit_denominator=None, max_digits=5),
        ),
    ]
