# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 02:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0005_auto_20170208_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcategory',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='ingredientsubcategory',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='distillery',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Wikipedia URL'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='own_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Manufacturer URL'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='us_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True, verbose_name='state'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='wiki_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Wikipedia URL'),
        ),
    ]
