# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0008_auto_20170214_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='base_spirit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cocktails', to='cocktails.Ingredient'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
    ]
