# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 00:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0009_auto_20170214_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amazon_url_uk',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Amazon UK URL'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='amazon_url_us',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Amazon US URL'),
        ),
        migrations.AddField(
            model_name='tool',
            name='amazon_url_uk',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Amazon UK URL'),
        ),
        migrations.AddField(
            model_name='tool',
            name='amazon_url_us',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='Amazon US URL'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
    ]
