# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0010_auto_20170214_0012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktail',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='cocktailcategory',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='glassware',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='ingredientcategory',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='ingredientclass',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='ingredientsubcategory',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='preparationmethod',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='own_url',
        ),
        migrations.RemoveField(
            model_name='tool',
            name='own_url',
        ),
        migrations.AlterField(
            model_name='cocktail',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='cocktailcategory',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='distillery',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='glassware',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
        migrations.AlterField(
            model_name='ingredientcategory',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientclass',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='ingredientsubcategory',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='preparationmethod',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='tool',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='plural',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
