# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 02:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0011_auto_20170217_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Image URL')),
                ('wiki_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Wikipedia URL')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('us_state', localflavor.us.models.USStateField(blank=True, max_length=2, null=True)),
                ('city', models.CharField(blank=True, max_length=60, null=True)),
                ('year_established', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2017), django.core.validators.MinValueValidator(1600)])),
                ('distillery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='cocktails.Distillery')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='brands', to='cocktails.Manufacturer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='distillery',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.Brand'),
        ),
    ]
