# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 04:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0013_auto_20170302_0324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cocktailcategory',
            name='method',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
    ]
