# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0014_auto_20170303_0442'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('image_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Image URL')),
                ('wiki_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='Wikipedia URL')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='wiki_url',
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='glassware',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to='cocktails.Glassware'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='cocktails.Source'),
            preserve_default=False,
        ),
    ]
