# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 00:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cocktails', '0016_auto_20170306_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unitofmeasure',
            old_name='name',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='unitofmeasure',
            old_name='plural',
            new_name='display_plural',
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='verbose_name',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unitofmeasure',
            name='verbose_plural',
            field=models.CharField(default='', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='subcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='cocktails.IngredientSubcategory'),
        ),
    ]
